### ISSUE TITLE
1.14.1 paper not compatible

### ISSUE THREAD

**Issue by kopper45** [Rocologo/MobHunting#503]
I recently switched my server to Paper and I updated to the latest version of the plugin and it no longer seems to be compatible with my server. I downgraded to 6.5.6 and it seems to work just fine, but when i update to 6.5.7 the plugin appears red and the commands no longer work.

**Comment by Rocologo** [comment]
Please check the server log for errors.

**Comment by Rocologo** [comment]
I need more information to help you?

**Comment by kopper45** [comment]
23:01:22] [Server thread/INFO]: [EssentialsProtect] Enabling EssentialsProtect v2.16.1.154
[23:01:22] [Server thread/INFO]: [EssentialsProtect] Continuing to enable Protect.
[23:01:22] [Server thread/INFO]: [MobHunting] Enabling MobHunting v6.5.7
[23:01:22] [Server thread/INFO]: [MobHunting] Your config version is 1
[23:01:23] [Server thread/INFO]: [MobHunting] Existing config.yml loaded.
[23:01:23] [Server thread/INFO]: [MobHunting] Config.yml was backed up to plugins\MobHunting\backup\config.yml.bak42
[23:01:23] [Server thread/ERROR]: Error occurred while enabling MobHunting v6.5.7 (Is it up to date?)
java.lang.NoClassDefFoundError: one/lindegaard/Core/WorldGroupManager
	at one.lindegaard.MobHunting.MobHunting.onEnable(MobHunting.java:179) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.1.jar:git-Paper-23]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.1.jar:git-Paper-23]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:419) ~[patched_1.14.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-23]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:378) ~[patched_1.14.1.jar:git-Paper-23]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:464) ~[patched_1.14.1.jar:git-Paper-23]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.14.1.jar:git-Paper-23]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:843) ~[patched_1.14.1.jar:git-Paper-23]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: one.lindegaard.Core.WorldGroupManager
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_211]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:139) ~[patched_1.14.1.jar:git-Paper-23]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[patched_1.14.1.jar:git-Paper-23]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
	... 10 more
[23:01:23] [Server thread/INFO]: [MobHunting] Disabling MobHunting v6.5.7

**Comment by Rocologo** [comment]
Upgrade MobHunting. This bug is fixed.
