### ISSUE TITLE
Not working :(

### ISSUE THREAD

**Issue by Yomatsusshimano** [Rocologo/MobHunting#92]
This error upon killing monster. Running 1.7.10 mod with up to date thermos.

`[12:51:05 ERROR]: Could not pass event EntityDeathEvent to MobHunting v3.4.3
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1072) [sv.class:?]
        at net.minecraft.entity.monster.EntitySkeleton.func_70645_a(EntitySkeleton.java:188) [yl.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
        at net.minecraft.entity.monster.EntityMob.func_70097_a(EntityMob.java:71) [yg.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) [mw.class:?]
        at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) [ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getName()Ljava/lang/String;
        at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:1034) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 22 more`

**Comment by Yomatsusshimano** [comment]
The special bonus' work, such as getting a skelly to kill another skelly.

**Comment by Rocologo** [comment]
It is the same error:

java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getName()Ljava/lang/String; 

I have never tried Thermos, so it will take some time to investigate this.

**Comment by Rocologo** [comment]
PLease test Build 100 or newer on my Jenkins server:

http://jenkins.lindegaard.one:8180/job/MobHunting/

**Comment by Yomatsusshimano** [comment]
Will that work with 1.7.10?

**Comment by Yomatsusshimano** [comment]
Now I can see the gold bars on the ground but no money is shown above it and it doesn't add to my balance.


`[12:41:19 INFO]: Given [Zombie Head] * 1 to Yomatsu
[12:41:19 INFO]: CONSOLE issued server command: /give Yomatsu iron_ingot 1
[12:41:19 INFO]: Giving 1 of iron ingot to Yomatsu.
[12:41:41 ERROR]: Could not pass event EntityDeathEvent to MobHunting v3.4.4-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1072) [sv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) [mw.class:?]
        at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) [ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getName()Ljava/lang/String;
        at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:873) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 20 more
[12:41:43 ERROR]: Could not pass event EntityDeathEvent to MobHunting v3.4.4-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1072) [sv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) [mw.class:?]
        at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) [ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getName()Ljava/lang/String;
        at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:873) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 20 more
[12:41:47 ERROR]: Could not pass event EntityDeathEvent to MobHunting v3.4.4-SNAPSHOT
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:338) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [SimplePluginManager.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:360) [CraftEventFactory.class:1.7.10-1614.57]
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callEntityDeathEvent(CraftEventFactory.java:353) [CraftEventFactory.class:1.7.10-1614.57]
        at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:1076) [sv.class:?]
        at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:978) [sv.class:?]
        at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1399) [yz.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.localAttackTargetEntityWithCurrentItem(EntityPlayerMP.java) [mw.class:?]
        at api.player.server.ServerPlayerAPI.attackTargetEntityWithCurrentItem(Unknown Source) [ServerPlayerAPI.class:?]
        at net.minecraft.entity.player.EntityPlayerMP.func_71059_n(EntityPlayerMP.java) [mw.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:1611) [nh.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
        at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) [ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.LivingEntity.getName()Ljava/lang/String;
        at one.lindegaard.MobHunting.MobHunting.onMobDeath(MobHunting.java:873) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_101]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_101]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:334) ~[JavaPluginLoader$1.class:1.7.10-1614.57]
        ... 21 more
[12:41:56 INFO]: Yomatsu issued server command: /money`

**Comment by Rocologo** [comment]
You have to setdropmoneyonground = false in config.yml

But it looks like you found a bug too. 
 org.bukkit.entity.LivingEntity.getName

**Comment by Yomatsusshimano** [comment]
> You have to setdropmoneyonground = false in config.yml
No I want the money to drop, which it is, but I thought it displayed the amount above the ingot on the ground?

> But it looks like you found a bug too.
org.bukkit.entity.LivingEntity.getName

Yeah, I keep having problems and finding bugs I guess..

**Comment by Rocologo** [comment]
Please try newest build  on the Jenkins server (102)

I have very few 1.7.10 server-owners how uses MobHunting. 5 at the moment (http://mcstats.org/plugin/MobHunting) and if they dont report the problems i cant fix them. So with some patience I will fix the bugs on 1.7.10 servers.

**Comment by Rocologo** [comment]
V 1.7.10 does not support customtext above the items. And I had some problems with the dropOnGroupMoney. I will have to look at that problem, when we have found all basic problems.

**Comment by Yomatsusshimano** [comment]
Ahh understood. Testing now. I'll report back ASAP.

**Comment by Rocologo** [comment]
Maybe you are lucky. I just saw this error in the console. This helps me to fix the dropMoneyOnGround

Plugin MobHunting v3.4.4-SNAPSHOT has failed to register events for class one.lindegaard.MobHunting.rewards.Rewards because org/bukkit/event/entity/ItemMergeEvent does not exist.

**Comment by Yomatsusshimano** [comment]
No errors yet with #102. Is the dropMoneyOnGround bug going to be #103?

**Comment by Rocologo** [comment]
Yes. You were lucky.. DropMoneyOnGround works in Build 103 :-)

**Comment by Rocologo** [comment]
But I will not be able to put the number above the item. No matter what. 1.7.10 does nu support this.

**Comment by Yomatsusshimano** [comment]
Yep, Seems to be working! Other than the number above the item but that's quite alright :) Thanks!

**Comment by Rocologo** [comment]
I wait some days before I release the offical V3.4.4 in case you find more bugs :-|

**Comment by Yomatsusshimano** [comment]
Roger that.

**Comment by Rocologo** [comment]
V3.4.4 released.
