### ISSUE TITLE
V3.08 not working on Spigot 1.8.8

### ISSUE THREAD

**Issue by HairyDaddy** [Rocologo/MobHunting#49]
This issues right after the server successfully loads: `[12:22:36] [Craft Scheduler Thread - 4/WARN]: Exception in thread "Craft Scheduler Thread - 4" 
[12:22:36] [Craft Scheduler Thread - 4/WARN]: org.apache.commons.lang.UnhandledException: Plugin MobHunting v3.0.8 generated an exception while executing task 40
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensAPI
	at one.lindegaard.MobHunting.compatability.CitizensCompat.isCitizensSupported(CitizensCompat.java:165)
	at one.lindegaard.MobHunting.MetricsManager$4.getValue(MetricsManager.java:69)
	at org.mcstats.Metrics.postPlugin(Metrics.java:411)
	at org.mcstats.Metrics.access$4(Metrics.java:350)
	at org.mcstats.Metrics$1.run(Metrics.java:245)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more
Caused by: java.lang.ClassNotFoundException: net.citizensnpcs.api.CitizensAPI
	at java.net.URLClassLoader.findClass(Unknown Source)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 10 more`
This is what I got when a mob spawned nearby: http://pastebin.com/CxzgKHMg

Current version is unable to work properly on Spigot 1.8.8 running Vault 1.5.6, however 3.0.7 and seemingly older versions are working just fine. So keep that in mind.

**Comment by Rocologo** [comment]
This is fixedin v3.1.0. I made a small change in v3.0.8 and forgot to check what happened if Citizens was NOT installed. Like in your case. Install 3.1.0 and problem is solved.
